[package]
name = "rtodo"
version = "0.1.0"
edition = "2024"



 [dependencies]
 ratatui = "0.29"
 crossterm = "0.28"
 color-eyre = "0.6"
 chrono = { version = "0.4", features = ["serde"] }
 serde = { version = "1.0", features = ["derive"] }
 serde_json = "1.0"
